version: 0.0
os: linux
files:
  - source: /
    destination: /web/current
file_exists_behavior: OVERWRITE

permissions:
  - object: /web/current
    pattern: "**"
    owner: root
    group: apache

  - object: /web/current/devops/scripts
    pattern: "**"
    except: [/web/current/devops/scripts/files]
    mode: 777
    type:
        - file

hooks:
  AfterInstall:
    - location: /web/current/devops/scripts/InstallingTex2ImgRequisites.sh
    - location: /web/current/devops/scripts/settingSlimerjsPermission.sh
      timeout: 300
      runas: root

 # AfterAllowTraffic:

  ApplicationStart:
    - location: /web/current/devops/scripts/phpStgConfiguration.sh
      timeout: 300
      runas: root
